### ISSUE TITLE
Need for proper message in reply on validation error

### ISSUE THREAD

**Issue by akashgupta88** [pebble/joi-objectid#3]
The message returned from a validation error is of the following format.

    "user_id fails to match the required pattern"

Is there a way we could put in a more intuitive, custom message, like:

    "user_id needs to be a valid objectID"

**Comment by aheckmann** [comment]
The returned object is a Joi string object so anything Joi strings supports
we support. Check out the Joi docs. https://github.com/hapijs/joi

On Monday, February 23, 2015, Akash Gupta <notifications@github.com> wrote:

> The message returned from a validation error is of the following format.
>
> "user_id fails to match the required pattern"
>
> Is there a way we could put in a more intuitive, custom message, like:
>
> "user_id needs to be a valid objectID"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pebble/joi-objectid/issues/3>.
>


-- 
Aaron Heckmann
Web Development Lead :: Pebble
https://github.com/aheckmann
https://twitter.com/aaronheckmann

**Comment by akashgupta88** [comment]
There is no support for custom error messages in Joi! At least I could not find any.
